### ISSUE TITLE
GAMES - Details affichage vignettes

### ISSUE THREAD

**Issue by wuthrer** [tonifisler/epicgamejam#18]
Par rapport à la maquette, il y aurait quelques petits changements à faire. À voir si tu penses que ça rendrait mieux que maintenant.

![vignettes](https://cloud.githubusercontent.com/assets/7643262/8150341/fb289cba-12e5-11e5-818b-0c8e295fc32f.jpg)
1) Ajuster le contour sur le nombre d'epic points et le mot epic points lui-même pour que ça devienne une ombre portée, pas juste un contour.
2) Calé les badges sur la droite, pourquoi pas en plus petit.
3) Rajouter la liste des genres taggés sur le jeu, après son titre et son auteur.

Un truc en option mais qui rajoute un peu de fancyness et de cohérence:
![hoverignettes](https://cloud.githubusercontent.com/assets/7643262/8150411/c60a34aa-12e8-11e5-8f5d-16af50e304ba.jpg)
Rajouter un effet de blanc transparent qui se rajoute sur les images quand les gens sont en hover dessus => blanc = tu peux cliquer.

**Comment by tonifisler** [comment]
> Ajuster le contour sur le nombre d'epic points et le mot epic points lui-même pour que ça devienne une ombre portée, pas juste un contour.

Question lisibilité selon le fond derrière, je ne vais pas enlever le contour. Par contre je peux pousser une partie de l'ombre (il y en a déjà une petite) sur la droite.

**Avant:**
![screen shot 2015-06-16 at 07 52 33](https://cloud.githubusercontent.com/assets/1708450/8176593/b3737e22-13fc-11e5-9001-c638c7c95089.png)

**Après:**
![screen shot 2015-06-16 at 07 52 18](https://cloud.githubusercontent.com/assets/1708450/8176594/bb4ee37a-13fc-11e5-8e4c-901a3b77bc6e.png)

``` css
text-shadow: 2px 2px 0 #231f20, -1px -1px 0 #231f20, 1px -1px 0 #231f20, -1px 1px 0 #231f20, 3px 2px 0 #231f20;
```

---

> Calé les badges sur la droite, pourquoi pas en plus petit.

Et sur une tablette? Un mobile? :stuck_out_tongue_winking_eye: 

---

> Rajouter la liste des genres taggés sur le jeu, après son titre et son auteur.

Ok. Mais pareil, je peux bien mettre "après", mais ça le sera que sur desktop.

---

> Rajouter un effet de blanc transparent qui se rajoute sur les images quand les gens sont en hover dessus

Nope. Mettre un effet sur l'image je veux bien, mais le truc que tu changes en blanc n'est pas cliquable. On a une foule de liens sur ces vignettes de jeux, c'est pas trop possible de faire des effets hover généraux. Je vais faire une proposition.

### TODO
- [x] change `text-shadow` property of `.text-epic` text
- [x] find a slightly better position for the badges (optional)
- [x] add genres in header
- [x] think about some hover effects on the teaser image and links

/ping @wuthrer

**Comment by wuthrer** [comment]
> Nope. Mettre un effet sur l'image je veux bien, mais le truc que tu changes en blanc n'est pas cliquable.

Juste, j'avais pas du tout réalisé que tous les trucs étaient clicables, au temps pour moi!

> Ok. Mais pareil, je peux bien mettre "après", mais ça le sera que sur desktop.

Ouais mais c'est pas plus mal. D'ailleurs, ma remarque qui va suivre fait aussi écho à 

> Et sur une tablette? Un mobile? :stuck_out_tongue_winking_eye:

Les badges sur la version mobile ça reste malheureusement assez anecdotique, dans le sens où il n' a pas le hover dessus (si je ne dis pas de conneries). Et ce d'autant plus dans la partie "epic games", parce qu'à part les connards qui vont  aller sur leur tablette en espérant pouvoir rejouer au remake de Candy Crush et soudainement réaliser qu'il n'y quasiment aucun jeu de n'importe quel jam qui tourne sur un device mobile, bha c'est dommage d'appauvrir le layout pour les gens qui vont concrètement pouvoir jouer aux jeux via web. Et j'ai aussi peur que certains jeux en aient beaucoup plus cette année (les badges), vu qu'on les affiche clairement pour la première fois, peut-être que certains vont essayer d'en récolter un maximum :dancer: 

> Question lisibilité selon le fond derrière, je ne vais pas enlever le contour. Par contre je peux pousser une partie de l'ombre (il y en a déjà une petite) sur la droite.

C'est peut-être juste un problème d'affichage sur Firefox du coup. Parce que sur ta screen le "avant" va très bien.
![github_toni1](https://cloud.githubusercontent.com/assets/7643262/8178043/1876f32c-140b-11e5-9954-e45dca7d795b.jpg)

**Comment by wuthrer** [comment]
Ah ouais, et juste un petit truc.

Il n'y a que les trois premiers bandeaux qui alternent entre les couleurs. Là de nouveau, c'est pas prioritaire, mais ça fait plus sympa.
